"""detail model changes

Revision ID: c184631bfdab
Revises: 2c46aed6316c
Create Date: 2025-01-17 15:54:31.959606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c184631bfdab'
down_revision: Union[str, None] = '2c46aed6316c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('details', 'attempts')
    op.drop_column('details', 'startdate')
    op.drop_column('details', 'enddate')
    op.drop_column('details', 'successful')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details', sa.Column('successful', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('details', sa.Column('enddate', mysql.DATETIME(), nullable=True))
    op.add_column('details', sa.Column('startdate', mysql.DATETIME(), nullable=True))
    op.add_column('details', sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('details', 'timestamp')
    # ### end Alembic commands ###
